### ISSUE TITLE
Errors, when destroying a pool

### ISSUE THREAD

**Issue by sheremet-va** [tinylibs/tinypool#43]
Reproduction: https://github.com/sheremet-va/vitest/tree/bug/pool-destroy

Steps to reproduce:

> Run `pnpm run build` to build Vitest
> Run `pnpm run test` to start tests
> When you see "Vitest" label, hit `Ctrl+C`
> See errors:

```
Exception in PromiseRejectCallback:
node:internal/process/task_queues:104
function nextTick(callback) {
                 ^

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
file:///Users/sheremet.mac/Projects/vitest/node_modules/.pnpm/tinypool@0.3.0/node_modules/tinypool/dist/esm/index.js:636
        reject(err);
        ^

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
node:internal/worker:366
    return new Promise((resolve) => {
           ^

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
file:///Users/sheremet.mac/Projects/vitest/node_modules/.pnpm/tinypool@0.3.0/node_modules/tinypool/dist/esm/index.js:636
        reject(err);
        ^

RangeError: Maximum call stack size exceeded
(node:42681) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [Worker]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
error during close RangeError: Maximum call stack size exceeded
    at Worker.terminate (node:internal/worker:345:12)
    at WorkerInfo.destroy (file:///Users/sheremet.mac/Projects/vitest/node_modules/.pnpm/tinypool@0.3.0/node_modules/tinypool/dist/esm/index.js:371:17)
    at ThreadPool._removeWorker (file:///Users/sheremet.mac/Projects/vitest/node_modules/.pnpm/tinypool@0.3.0/node_modules/tinypool/dist/esm/index.js:589:16)
    at file:///Users/sheremet.mac/Projects/vitest/node_modules/.pnpm/tinypool@0.3.0/node_modules/tinypool/dist/esm/index.js:641:14
    at TaskInfo.runInAsyncScope (node:async_hooks:203:9)
    at TaskInfo.done (file:///Users/sheremet.mac/Projects/vitest/node_modules/.pnpm/tinypool@0.3.0/node_modules/tinypool/dist/esm/index.js:251:10)
    at WorkerInfo.destroy (file:///Users/sheremet.mac/Projects/vitest/node_modules/.pnpm/tinypool@0.3.0/node_modules/tinypool/dist/esm/index.js:376:16)
    at ThreadPool._removeWorker (file:///Users/sheremet.mac/Projects/vitest/node_modules/.pnpm/tinypool@0.3.0/node_modules/tinypool/dist/esm/index.js:589:16)
    at file:///Users/sheremet.mac/Projects/vitest/node_modules/.pnpm/tinypool@0.3.0/node_modules/tinypool/dist/esm/index.js:641:14
    at TaskInfo.runInAsyncScope (node:async_hooks:203:9)
```

**Comment by Aslemammad** [comment]
Thank you so much, I'll put some time on this and the other issue this weekend.
