### ISSUE TITLE
ERR_IPC_CHANNEL_CLOSED: Channel closed

### ISSUE THREAD

**Issue by AriPerkkio** [tinylibs/tinypool#94]
Error below comes up quite often on Vitest's codebase. Tests themselves are passing fine, but this error is visible on test logs. My initial guess is that Tinypool is shutting down before workers have finished loading user's entrypoint. These workers are likely the idle workers that are kept ready for next pool runs.

These errors should only come up when multiple pools are nested, e.g. running Tinypool in Tinypool. 

```
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at target.send (node:internal/child_process:754:16)
    at file:///<root>/vitest/node_modules/.pnpm/tinypool@0.9.0/node_modules/tinypool/dist/entry/process.js:29:7
Emitted 'error' event on process instance at:
    at node:internal/child_process:758:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```

As fix we could try adding a no-op callback here just to ignore these errors:

https://github.com/tinylibs/tinypool/blob/ea05a00c86d10465674b6747538c7b18902bd5ae/src/entry/process.ts#L42-L46

https://nodejs.org/api/process.html#processsendmessage-sendhandle-options-callback

**Comment by AriPerkkio** [comment]
Minimal repro:

```ts
import { isMainThread } from "node:worker_threads";
import Tinypool from "tinypool";

const isMainProcess = process.send === undefined;

if (isMainProcess && isMainThread) {
  console.log("Starting main pool");

  const pool = new Tinypool({
    filename: new URL(import.meta.url).href,
    isolateWorkers: true,
  });

  await Promise.all([
    pool.run({}, { name: "wrapper" }),
    pool.run({}, { name: "wrapper" }),
    pool.run({}, { name: "wrapper" }),
  ]);
}

export async function wrapper() {
  console.log("Starting nested pool");

  const pool = new Tinypool({
    filename: new URL(import.meta.url, import.meta.url).href,
    runtime: "child_process",
    isolateWorkers: true,
    minThreads: 8,
    maxThreads: 8,
  });

  await pool.run({ a: 4, b: 6 }, { name: "sum" });
  pool.recycleWorkers();
}

export async function sum({ a, b }) {
  console.log("Running worker");
  return a + b;
}
```

```
 $ node repro.mjs 
Starting main pool
Starting nested pool
Starting nested pool
Starting nested pool
Running worker
Running worker
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at target.send (node:internal/child_process:754:16)
    at file:///x/repros/node_modules/.pnpm/tinypool@0.9.0/node_modules/tinypool/dist/entry/process.js:29:7
Emitted 'error' event on process instance at:
    at node:internal/child_process:758:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v20.12.2
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at target.send (node:internal/child_process:754:16)
    at file:///x/repros/node_modules/.pnpm/tinypool@0.9.0/node_modules/tinypool/dist/entry/process.js:29:7
Emitted 'error' event on process instance at:
    at node:internal/child_process:758:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```
